# Generated by Django 4.1.1 on 2022-10-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='first_message',
            field=models.BooleanField(default=True),
        ),
    ]
