# Generated by Django 4.1.1 on 2022-10-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0005_rename_description_orders_observation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Observation',
            new_name='observation',
        ),
    ]
