# Generated by Django 4.1.1 on 2022-10-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0006_rename_observation_orders_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_products',
            name='total',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
